version: '3.8'
services:
  redis_server:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dalgo-network 
  backend:
    image: dalgo_backend:0.1
    command: backend
    restart: always
    ports:
      - "8002:8002"
    env_file:
      - .env
    networks:
      - dalgo-network
  celery_beat:
    image: dalgo_backend:0.1
    command: beat
    depends_on:
      - backend
      - redis_server
    env_file:
      - .env
    volumes:
      - celerybeat_volume:/data
    networks:
      - dalgo-network

  celery_worker:
    image: dalgo_backend:0.1
    command: worker
    depends_on:
      - backend
      - redis_server
    env_file:
      - .env
    volumes:
      - celerybeat_worker:/data
    networks:
      - dalgo-network

volumes:
  redis_data:
  celerybeat_volume:
  celerybeat_worker:

networks:
  dalgo-network:
    driver: bridge
